### ISSUE TITLE
One Slot Tools is glitched

### ISSUE THREAD

**Issue by OtavioAugusto04** [MetallicGoat/MBedwarsTweaks#12]
One Slot Tools isn't working as intended. There are several glitches that affect the user's gameplay experience.

https://cdn.discordapp.com/attachments/822282740765294613/1031926217449947206/Badlion_Minecraft_Client_v3.11.4-107c04c-PRODUCTION3_1.8.9_2022-10-18_10-44-35.mp4

The video is not mine but it illustrates the problem perfectly.

**Comment by MetallicGoat** [comment]
I'm aware of the issues with it. I have a build that fixes most of them, however it requires 5.0.15. I am waiting for it to be released before I release the tweaks update to fix the bugs

**Comment by MetallicGoat** [comment]
As of 5.1.1, one-slot-tools will be baked directly into MBedwars. It should resolve the issue you are experiencing :)
