### ISSUE TITLE
Different Names for the Addon

### ISSUE THREAD

**Issue by LeNinjaHD** [MetallicGoat/MBedwarsTweaks#7]
I noticed, that this addon has 2 Names, MBedWarsTweaks and Tweaks-and-Features.

Which one is the right one?

**Comment by MetallicGoat** [comment]
Have not really decided lol

**Comment by LeNinjaHD** [comment]
I prefer MBedWarsTweaks, bc it suggests the connection to MBedWars

**Comment by MetallicGoat** [comment]
Yeah that's what I normally call it. Or also just 'the tweaks addon'
